## Hospital Appointment & Billing Analysis

## Part A - Initial Inspection

#### Load the CSV into df. Display the first 10 rows, shape, columns, dtypes, and info().

In [53]:
import pandas as pd

In [54]:
df=pd.read_csv("case3_hospital_appointments_raw.csv")
df.head(10)

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,12-08-2026,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,thirty eight,12/08/2026,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,13-08-2026,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,13/08/2026,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34,bad date,14:00,800,Pending,Yes,Not Rated
5,A006,Arjun Rao,Orthopedics,Surat,52,14-08-2026,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41,14/08/2026,10:45,NaN,Paid,TRUE,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60,15-08-2026,11:30,1200,Cancelled,FALSE,3.9
8,A009,Kavya Nair,ENT,Surat,27,15/08/2026,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48,16-08-2026,09:45,1500,Pending,No,4.1

In [55]:
df.shape

(20, 11)

In [56]:
df.columns

Index(['Appointment_ID', 'Patient_Name', 'Department', 'City', 'Age',
       'Appointment_Date', 'Time', 'Fee', 'Payment_Status', 'Insurance',
       'Rating'],
      dtype='str')

In [57]:
df.dtypes

Appointment_ID      str
Patient_Name        str
Department          str
City                str
Age                 str
Appointment_Date    str
Time                str
Fee                 str
Payment_Status      str
Insurance           str
Rating              str
dtype: object

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Appointment_ID    20 non-null     str
 1   Patient_Name      20 non-null     str
 2   Department        20 non-null     str
 3   City              20 non-null     str
 4   Age               19 non-null     str
 5   Appointment_Date  20 non-null     str
 6   Time              20 non-null     str
 7   Fee               19 non-null     str
 8   Payment_Status    20 non-null     str
 9   Insurance         20 non-null     str
 10  Rating            20 non-null     str
dtypes: str(11)
memory usage: 1.8 KB

#### Identify at least five data-quality or data-type problems visible in the file.

In [59]:
# thirty eight → invalid age format
# bad date → invalid date
# 1,500 → inconsistent fee format
# Yes/Y/TRUE → inconsistent insurance categories
# Not Rated → invalid/missing rating value

#### Create a working copy named df_clean.

In [60]:
df_clean=df.copy()
df_clean.head()

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,12-08-2026,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,thirty eight,12/08/2026,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,13-08-2026,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,13/08/2026,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34,bad date,14:00,800,Pending,Yes,Not Rated

## Part B - Chapter 5: Data Type Conversion

#### Remove leading/trailing spaces from Patient_Name.

In [61]:
df["Patient_Name"] = df["Patient_Name"].str.strip()
df.head()

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,12-08-2026,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,thirty eight,12/08/2026,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,13-08-2026,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,13/08/2026,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34,bad date,14:00,800,Pending,Yes,Not Rated

#### Convert Age safely to a nullable integer. Invalid age text must become missing.

In [64]:
df["Age"] = pd.to_numeric(df["Age"],errors='coerce').astype("Int32")

In [65]:
df.head()

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,12-08-2026,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,<NA>,12/08/2026,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,13-08-2026,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,<NA>,13/08/2026,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34,bad date,14:00,800,Pending,Yes,Not Rated

####  Clean Fee values containing commas/spaces and convert Fee to numeric.

In [71]:
df["Fee"] = pd.to_numeric(df["Fee"].astype(str).str.replace(',','').str.strip(),errors='coerce').astype("Int32")
df["Fee"].dtypes

Int32Dtype()

#### Convert Appointment_Date to datetime using the mixed day-first formats. Invalid dates should become NaT.