In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("customer.csv")
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le=LabelEncoder()

In [5]:
le.fit_transform(df[["purchased"]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [6]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [8]:
df["purchased"]=le.fit_transform(df[["purchased"]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [9]:
df

    age  gender   review education  purchased
0    30  Female  Average    School          0
1    68  Female     Poor        UG          0
2    70  Female     Good        PG          0
3    72  Female     Good        PG          0
4    16  Female  Average        UG          0
5    31  Female  Average    School          1
6    18    Male     Good    School          0
7    60  Female     Poor    School          1
8    65  Female  Average        UG          0
9    74    Male     Good        UG          1
10   98  Female     Good        UG          1
11   74    Male     Good        UG          1
12   51    Male     Poor    School          0
13   57  Female  Average    School          0
14   15    Male     Poor        PG          1
15   75    Male     Poor        UG          0
16   59    Male     Poor        UG          1
17   22  Female     Poor        UG          1
18   19    Male     Good    School          0
19   97    Male     Poor        PG          1
20   57  Female  Average    School          1
21   32    Male  Average        PG          0
22   18  Female     Poor        PG          1
23   96  Female     Good    School          0
24   16  Female  Average        PG          1
25   57  Female     Good    School          0
26   53  Female     Poor        PG          0
27   69  Female     Poor        PG          0
28   48    Male     Poor    School          0
29   83  Female  Average        UG          1
30   73    Male  Average        UG          0
31   22  Female     Poor    School          1
32   92    Male  Average        UG          1
33   89  Female     Good        PG          1
34   86    Male  Average    School          0
35   74    Male     Poor    School          1
36   34  Female     Good        UG          1
37   94    Male  Average        PG          1
38   45  Female     Good    School          0
39   76    Male     Poor        PG          0
40   39    Male     Good    School          0
41   23    Male     Good        PG          1
42   30  Female     Good        PG          1
43   27    Male     Poor        PG          0
44   77  Female  Average        UG          0
45   61    Male     Poor        PG          1
46   64  Female     Poor        PG          0
47   38  Female     Good        PG          1
48   39  Female     Good        UG          1
49   25  Female     Good        UG          0

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df["education"].nunique()

3

In [13]:
df["education"].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [14]:
df["review"].nunique()

3

In [15]:
df["review"].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [16]:
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [17]:
oe.fit_transform(df[["review","education"]])

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [18]:
df[["review","education"]]=oe.fit_transform(df[["review","education"]])
df

    age  gender  review  education  purchased
0    30  Female     1.0        0.0          0
1    68  Female     0.0        1.0          0
2    70  Female     2.0        2.0          0
3    72  Female     2.0        2.0          0
4    16  Female     1.0        1.0          0
5    31  Female     1.0        0.0          1
6    18    Male     2.0        0.0          0
7    60  Female     0.0        0.0          1
8    65  Female     1.0        1.0          0
9    74    Male     2.0        1.0          1
10   98  Female     2.0        1.0          1
11   74    Male     2.0        1.0          1
12   51    Male     0.0        0.0          0
13   57  Female     1.0        0.0          0
14   15    Male     0.0        2.0          1
15   75    Male     0.0        1.0          0
16   59    Male     0.0        1.0          1
17   22  Female     0.0        1.0          1
18   19    Male     2.0        0.0          0
19   97    Male     0.0        2.0          1
20   57  Female     1.0        0.0          1
21   32    Male     1.0        2.0          0
22   18  Female     0.0        2.0          1
23   96  Female     2.0        0.0          0
24   16  Female     1.0        2.0          1
25   57  Female     2.0        0.0          0
26   53  Female     0.0        2.0          0
27   69  Female     0.0        2.0          0
28   48    Male     0.0        0.0          0
29   83  Female     1.0        1.0          1
30   73    Male     1.0        1.0          0
31   22  Female     0.0        0.0          1
32   92    Male     1.0        1.0          1
33   89  Female     2.0        2.0          1
34   86    Male     1.0        0.0          0
35   74    Male     0.0        0.0          1
36   34  Female     2.0        1.0          1
37   94    Male     1.0        2.0          1
38   45  Female     2.0        0.0          0
39   76    Male     0.0        2.0          0
40   39    Male     2.0        0.0          0
41   23    Male     2.0        2.0          1
42   30  Female     2.0        2.0          1
43   27    Male     0.0        2.0          0
44   77  Female     1.0        1.0          0
45   61    Male     0.0        2.0          1
46   64  Female     0.0        2.0          0
47   38  Female     2.0        2.0          1
48   39  Female     2.0        1.0          1
49   25  Female     2.0        1.0          0

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe=OneHotEncoder(sparse_output=False,drop="first")

In [22]:
ohe.fit_transform(df[["gender"]])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
encoded=ohe.fit_transform(df[["gender"]])

In [24]:
encoded_df=pd.DataFrame(encoded,columns=ohe.get_feature_names_out(["gender"]))
encoded_df

    gender_Male
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
5           0.0
6           1.0
7           0.0
8           0.0
9           1.0
10          0.0
11          1.0
12          1.0
13          0.0
14          1.0
15          1.0
16          1.0
17          0.0
18          1.0
19          1.0
20          0.0
21          1.0
22          0.0
23          0.0
24          0.0
25          0.0
26          0.0
27          0.0
28          1.0
29          0.0
30          1.0
31          0.0
32          1.0
33          0.0
34          1.0
35          1.0
36          0.0
37          1.0
38          0.0
39          1.0
40          1.0
41          1.0
42          0.0
43          1.0
44          0.0
45          1.0
46          0.0
47          0.0
48          0.0
49          0.0

In [25]:
df=pd.concat([encoded_df,df],axis=1)
df

    gender_Male  age  gender  review  education  purchased
0           0.0   30  Female     1.0        0.0          0
1           0.0   68  Female     0.0        1.0          0
2           0.0   70  Female     2.0        2.0          0
3           0.0   72  Female     2.0        2.0          0
4           0.0   16  Female     1.0        1.0          0
5           0.0   31  Female     1.0        0.0          1
6           1.0   18    Male     2.0        0.0          0
7           0.0   60  Female     0.0        0.0          1
8           0.0   65  Female     1.0        1.0          0
9           1.0   74    Male     2.0        1.0          1
10          0.0   98  Female     2.0        1.0          1
11          1.0   74    Male     2.0        1.0          1
12          1.0   51    Male     0.0        0.0          0
13          0.0   57  Female     1.0        0.0          0
14          1.0   15    Male     0.0        2.0          1
15          1.0   75    Male     0.0        1.0          0
16          1.0   59    Male     0.0        1.0          1
17          0.0   22  Female     0.0        1.0          1
18          1.0   19    Male     2.0        0.0          0
19          1.0   97    Male     0.0        2.0          1
20          0.0   57  Female     1.0        0.0          1
21          1.0   32    Male     1.0        2.0          0
22          0.0   18  Female     0.0        2.0          1
23          0.0   96  Female     2.0        0.0          0
24          0.0   16  Female     1.0        2.0          1
25          0.0   57  Female     2.0        0.0          0
26          0.0   53  Female     0.0        2.0          0
27          0.0   69  Female     0.0        2.0          0
28          1.0   48    Male     0.0        0.0          0
29          0.0   83  Female     1.0        1.0          1
30          1.0   73    Male     1.0        1.0          0
31          0.0   22  Female     0.0        0.0          1
32          1.0   92    Male     1.0        1.0          1
33          0.0   89  Female     2.0        2.0          1
34          1.0   86    Male     1.0        0.0          0
35          1.0   74    Male     0.0        0.0          1
36          0.0   34  Female     2.0        1.0          1
37          1.0   94    Male     1.0        2.0          1
38          0.0   45  Female     2.0        0.0          0
39          1.0   76    Male     0.0        2.0          0
40          1.0   39    Male     2.0        0.0          0
41          1.0   23    Male     2.0        2.0          1
42          0.0   30  Female     2.0        2.0          1
43          1.0   27    Male     0.0        2.0          0
44          0.0   77  Female     1.0        1.0          0
45          1.0   61    Male     0.0        2.0          1
46          0.0   64  Female     0.0        2.0          0
47          0.0   38  Female     2.0        2.0          1
48          0.0   39  Female     2.0        1.0          1
49          0.0   25  Female     2.0        1.0          0

In [26]:
df.drop(["gender"],axis=1,inplace=True)
df

    gender_Male  age  review  education  purchased
0           0.0   30     1.0        0.0          0
1           0.0   68     0.0        1.0          0
2           0.0   70     2.0        2.0          0
3           0.0   72     2.0        2.0          0
4           0.0   16     1.0        1.0          0
5           0.0   31     1.0        0.0          1
6           1.0   18     2.0        0.0          0
7           0.0   60     0.0        0.0          1
8           0.0   65     1.0        1.0          0
9           1.0   74     2.0        1.0          1
10          0.0   98     2.0        1.0          1
11          1.0   74     2.0        1.0          1
12          1.0   51     0.0        0.0          0
13          0.0   57     1.0        0.0          0
14          1.0   15     0.0        2.0          1
15          1.0   75     0.0        1.0          0
16          1.0   59     0.0        1.0          1
17          0.0   22     0.0        1.0          1
18          1.0   19     2.0        0.0          0
19          1.0   97     0.0        2.0          1
20          0.0   57     1.0        0.0          1
21          1.0   32     1.0        2.0          0
22          0.0   18     0.0        2.0          1
23          0.0   96     2.0        0.0          0
24          0.0   16     1.0        2.0          1
25          0.0   57     2.0        0.0          0
26          0.0   53     0.0        2.0          0
27          0.0   69     0.0        2.0          0
28          1.0   48     0.0        0.0          0
29          0.0   83     1.0        1.0          1
30          1.0   73     1.0        1.0          0
31          0.0   22     0.0        0.0          1
32          1.0   92     1.0        1.0          1
33          0.0   89     2.0        2.0          1
34          1.0   86     1.0        0.0          0
35          1.0   74     0.0        0.0          1
36          0.0   34     2.0        1.0          1
37          1.0   94     1.0        2.0          1
38          0.0   45     2.0        0.0          0
39          1.0   76     0.0        2.0          0
40          1.0   39     2.0        0.0          0
41          1.0   23     2.0        2.0          1
42          0.0   30     2.0        2.0          1
43          1.0   27     0.0        2.0          0
44          0.0   77     1.0        1.0          0
45          1.0   61     0.0        2.0          1
46          0.0   64     0.0        2.0          0
47          0.0   38     2.0        2.0          1
48          0.0   39     2.0        1.0          1
49          0.0   25     2.0        1.0          0

In [ ]:
df=df[[]]