In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [3]:
df['number'].unique()

<StringArray>
['5', '3', '6', 'A', '2', '1', '4']
Length: 7, dtype: str

In [4]:
df['number_numeric']=pd.to_numeric(df['number'],errors='coerce',downcast='integer')

In [5]:
df['number_categorical'] = np.where(df['number_numeric'].isnull(),df['number'],np.nan)

df.head()

  Cabin            Ticket number  Survived  number_numeric number_categorical
0   NaN         A/5 21171      5         0             5.0                NaN
1   C85          PC 17599      3         1             3.0                NaN
2   NaN  STON/O2. 3101282      6         1             6.0                NaN
3  C123            113803      3         1             3.0                NaN
4   NaN            373450      A         0             NaN                  A

In [6]:
df['Cabin'].unique()

<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [9]:
df['Cabin_num'] = df['Cabin'].str.extract('(\d+)')
df['cabin_cat'] = df['Cabin'].str[0]

df.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\rajpr\AppData\Local\Temp\ipykernel_16572\1961317628.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Cabin_num'] = df['Cabin'].str.extract('(\d+)')

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,Cabin_num,cabin_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [11]:
df['Ticket_num'] = df['Ticket'].apply(lambda s : s.split()[-1])
df['Ticket_num'] = pd.to_numeric(df['Ticket_num'],errors='coerce',downcast='integer')


df['Ticket_cat'] = df['Ticket'].apply(lambda s : s.split()[-1])
df['Ticket_cat'] = np.where(df['Ticket_cat'].str.isdigit(),np.nan,df['Ticket_cat'])

df.head(10)

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,Cabin_num,cabin_cat,Ticket_num,Ticket_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,NaN
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN
5,NaN,330877,2,0,2.0,NaN,NaN,NaN,330877.0,NaN
6,E46,17463,2,0,2.0,NaN,46,E,17463.0,NaN
7,NaN,349909,5,0,5.0,NaN,NaN,NaN,349909.0,NaN
8,NaN,347742,1,1,1.0,NaN,NaN,NaN,347742.0,NaN
9,NaN,237736,A,1,NaN,A,NaN,NaN,237736.0,NaN

## Working with data and time