In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [3]:
df['number'].unique()

<StringArray>
['5', '3', '6', 'A', '2', '1', '4']
Length: 7, dtype: str

In [4]:
df['number_numeric']=pd.to_numeric(df['number'],errors='coerce',downcast='integer')

In [5]:
df['number_categorical'] = np.where(df['number_numeric'].isnull(),df['number'],np.nan)

df.head()

  Cabin            Ticket number  Survived  number_numeric number_categorical
0   NaN         A/5 21171      5         0             5.0                NaN
1   C85          PC 17599      3         1             3.0                NaN
2   NaN  STON/O2. 3101282      6         1             6.0                NaN
3  C123            113803      3         1             3.0                NaN
4   NaN            373450      A         0             NaN                  A

In [6]:
df['Cabin'].unique()

<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [9]:
df['Cabin_num'] = df['Cabin'].str.extract('(\d+)')
df['cabin_cat'] = df['Cabin'].str[0]

df.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\rajpr\AppData\Local\Temp\ipykernel_16572\1961317628.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Cabin_num'] = df['Cabin'].str.extract('(\d+)')

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,Cabin_num,cabin_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [11]:
df['Ticket_num'] = df['Ticket'].apply(lambda s : s.split()[-1])
df['Ticket_num'] = pd.to_numeric(df['Ticket_num'],errors='coerce',downcast='integer')


df['Ticket_cat'] = df['Ticket'].apply(lambda s : s.split()[-1])
df['Ticket_cat'] = np.where(df['Ticket_cat'].str.isdigit(),np.nan,df['Ticket_cat'])

df.head(10)

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,Cabin_num,cabin_cat,Ticket_num,Ticket_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,NaN
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN
5,NaN,330877,2,0,2.0,NaN,NaN,NaN,330877.0,NaN
6,E46,17463,2,0,2.0,NaN,46,E,17463.0,NaN
7,NaN,349909,5,0,5.0,NaN,NaN,NaN,349909.0,NaN
8,NaN,347742,1,1,1.0,NaN,NaN,NaN,347742.0,NaN
9,NaN,237736,A,1,NaN,A,NaN,NaN,237736.0,NaN

## Working with data and time

In [12]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [13]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [14]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [15]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [16]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [19]:
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [22]:
# extract year
date['year'] = date['date'].dt.year
date.head(2)

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018

In [ ]:
# extract month 
date['month'] = date['date'].dt.month
# if want month name then  date['month'] = date['date'].dt.month_name()
date.head

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [28]:
# extract days
date['days'] = date['date'].dt.day
date.head(2)

        date  product_id  city_id  orders  year  month  days
0 2019-12-10        5628       25       3  2019     12    10
1 2018-08-15        3646       14     157  2018      8    15

In [ ]:
# day of the week number
date['day_of_week'] = date['date'].dt.day_of_week
date.head(2)

        date  product_id  city_id  orders  year  month  days  day_of_week
0 2019-12-10        5628       25       3  2019     12    10            1
1 2018-08-15        3646       14     157  2018      8    15            2

In [32]:
# day of the week name
date['day_of_week'] = date['date'].dt.day_name()
date.head(2)

        date  product_id  city_id  orders  year  month  days day_of_week
0 2019-12-10        5628       25       3  2019     12    10     Tuesday
1 2018-08-15        3646       14     157  2018      8    15   Wednesday

In [34]:
# exttract week of the year
date['date_week'] = date['date'].dt.weekday
date.head(2)

,date,product_id,city_id,orders,year,month,days,day_of_week,date_week
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,1
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,2

In [35]:
# extract time gap between two dates
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 9, 13, 10, 30, 58, 80287)

In [37]:
today - date['date']

0     2469 days 10:30:58.080287
1     2951 days 10:30:58.080287
2     2882 days 10:30:58.080287
3     2584 days 10:30:58.080287
4     2807 days 10:30:58.080287
                 ...
995   2897 days 10:30:58.080287
996   2838 days 10:30:58.080287
997   2686 days 10:30:58.080287
998   2751 days 10:30:58.080287
999   2525 days 10:30:58.080287
Name: date, Length: 1000, dtype: timedelta64[us]

In [40]:
(today - date['date']).dt.days

0      2469
1      2951
2      2882
3      2584
4      2807
       ...
995    2897
996    2838
997    2686
998    2751
999    2525
Name: date, Length: 1000, dtype: int64

In [41]:
time.head(2)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826

In [42]:
time['date'] = pd.to_datetime(time['date'])

In [43]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB