### Feature Construction

Its an manual think there is no process in this we have to do it on domain knowledge and intuition<br><br>

### Feature Splitting

Here we make the data tidy ,i.e that in some dataset we might get more than one value in the same cell or we can say that there is no atomic value in an cell<br>
So in this case we use Featuer splitting to make it atomic

In [40]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [41]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [42]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [43]:
df.dropna(inplace=True)

In [44]:
X = df.iloc[:,0:4]
Y = df.iloc[:,-1]

In [45]:
np.mean(cross_val_score(LogisticRegression(),X,Y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

### Applying Feature Construction

In [46]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [47]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [48]:
def fun(num):
    if num == 1:
        #alone
        return 0
    elif num > 1 and  num <= 4:
        #small family
        return 1
    else:
        #large family
        return 2

In [49]:
X['family_type'] = X['Family_size'].apply(fun)

In [50]:
X.sample(5)

      Age  Pclass  SibSp  Parch  Family_size  family_type
663  36.0       3      0      0            1            0
120  21.0       2      2      0            3            1
676  24.5       3      0      0            1            0
24    8.0       3      3      1            5            2
212  22.0       3      0      0            1            0

In [51]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [52]:
X.head()

    Age  Pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [53]:
np.mean(cross_val_score(LogisticRegression(),X,Y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

After doing feature Construction we can see that there is little change in the accuracy on same model

## Feature Splitting

In [54]:
df_s = pd.read_csv("train.csv")

In [55]:
df_s['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [56]:
df_s['Title'] = df_s['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [57]:
df_s[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [59]:
(df_s.groupby('Title')['Survived'].mean()).sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

Through this we can analysis more on this dataset