In [2]:
import pandas as pd

Part A :Initial Inspection

In [3]:
df=pd.read_csv("retail_sales_practical.csv",)
print(df.head())
print(df.shape)

  Order_ID        Date   Product     Category       City  Quantity    Price  \
0     O101  01-07-2026    Laptop  Electronics      Surat       1.0  52000.0
1     O102  01-07-2026     Mouse  Electronics     Mumbai       3.0    700.0
2     O103  02-07-2026     Chair    Furniture      Surat       2.0   4500.0
3     O104  02-07-2026  Keyboard  Electronics  Ahmedabad       NaN   1500.0
4     O105  03-07-2026      Desk    Furniture      Surat       1.0      NaN

  Salesperson
0       Aarav
1        Diya
2       Rohan
3       Priya
4       Aarav
(36, 8)

In [4]:
df.columns # to display all the columns name in csv file

Index(['Order_ID', 'Date', 'Product', 'Category', 'City', 'Quantity', 'Price',
       'Salesperson'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     36 non-null     str
 1   Date         36 non-null     str
 2   Product      36 non-null     str
 3   Category     36 non-null     str
 4   City         36 non-null     str
 5   Quantity     35 non-null     float64
 6   Price        35 non-null     float64
 7   Salesperson  36 non-null     str
dtypes: float64(2), str(6)
memory usage: 2.4 KB

In [6]:
#some columns does have nan values which has to be taken care of

Part B :  Missing Value

In [7]:
missing_count=df.isnull().sum()
missing_count

Order_ID       0
Date           0
Product        0
Category       0
City           0
Quantity       1
Price          1
Salesperson    0
dtype: int64

In [8]:
df[df.isna().any(axis=1)] # to find rows with missing values

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson
3,O104,02-07-2026,Keyboard,Electronics,Ahmedabad,NaN,1500.0,Priya
4,O105,03-07-2026,Desk,Furniture,Surat,1.0,NaN,Aarav

In [9]:
missing_sum=df.isna().sum().sum()
missing_sum # finding total missing number of cells

np.int64(2)

In [10]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())
df.head()

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson
0,O101,01-07-2026,Laptop,Electronics,Surat,1.0,52000.0,Aarav
1,O102,01-07-2026,Mouse,Electronics,Mumbai,3.0,700.0,Diya
2,O103,02-07-2026,Chair,Furniture,Surat,2.0,4500.0,Rohan
3,O104,02-07-2026,Keyboard,Electronics,Ahmedabad,2.0,1500.0,Priya
4,O105,03-07-2026,Desk,Furniture,Surat,1.0,NaN,Aarav

In [11]:
furniture_median = df.loc[df['Category'] == 'Furniture', 'Price'].median()
df['Price'] = df['Price'].fillna(furniture_median)
print("Furniture median price:", furniture_median)

Furniture median price: 4950.0

In [12]:
df.isna().sum()

Order_ID       0
Date           0
Product        0
Category       0
City           0
Quantity       0
Price          0
Salesperson    0
dtype: int64

Part C :Duplicate Handling

In [13]:
df.duplicated().sum()

np.int64(2)

In [14]:
df[df.duplicated()]

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson
20,O103,02-07-2026,Chair,Furniture,Surat,2.0,4500.0,Rohan
21,O106,03-07-2026,Monitor,Electronics,Mumbai,2.0,12500.0,Diya

In [15]:
df[df.duplicated(subset=["Order_ID"])]

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson
20,O103,02-07-2026,Chair,Furniture,Surat,2.0,4500.0,Rohan
21,O106,03-07-2026,Monitor,Electronics,Mumbai,2.0,12500.0,Diya

In [16]:
#Missing Unique Identifier: A true duplicate check requires the Order_ID (or a combination of Order_ID + Timestamp). 
#Without checking the unique identifier, you cannot distinguish between a repeated event and a data entry error.

In [17]:
df.drop_duplicates(ignore_index=True,inplace=True)

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.shape

(34, 8)

Part D : Create a Sales Measure

In [20]:
df["Sales"]= df["Quantity"] * df["Price"]

In [21]:
df.head()

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson,Sales
0,O101,01-07-2026,Laptop,Electronics,Surat,1.0,52000.0,Aarav,52000.0
1,O102,01-07-2026,Mouse,Electronics,Mumbai,3.0,700.0,Diya,2100.0
2,O103,02-07-2026,Chair,Furniture,Surat,2.0,4500.0,Rohan,9000.0
3,O104,02-07-2026,Keyboard,Electronics,Ahmedabad,2.0,1500.0,Priya,3000.0
4,O105,03-07-2026,Desk,Furniture,Surat,1.0,4950.0,Aarav,4950.0

In [22]:
df[["Order_ID","Product","Quantity","Price","Sales"]].head(3)

  Order_ID Product  Quantity    Price    Sales
0     O101  Laptop       1.0  52000.0  52000.0
1     O102   Mouse       3.0    700.0   2100.0
2     O103   Chair       2.0   4500.0   9000.0

In [23]:
#its is used to find the product with most revenu generated one

Part E :Sorting

In [24]:
df.sort_values(by="Sales",ascending=False)

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson,Sales
0,O101,01-07-2026,Laptop,Electronics,Surat,1.0,52000.0,Aarav,52000.0
30,O131,16-07-2026,Projector,Electronics,Ahmedabad,1.0,42000.0,Rohan,42000.0
24,O125,13-07-2026,Smartphone,Electronics,Ahmedabad,1.0,34000.0,Aarav,34000.0
16,O117,09-07-2026,Tablet,Electronics,Surat,1.0,28000.0,Aarav,28000.0
5,O106,03-07-2026,Monitor,Electronics,Mumbai,2.0,12500.0,Diya,25000.0
9,O110,05-07-2026,Printer,Electronics,Ahmedabad,1.0,16500.0,Diya,16500.0
28,O129,15-07-2026,Meeting Table,Furniture,Surat,1.0,14500.0,Aarav,14500.0
17,O118,09-07-2026,Storage Cabinet,Furniture,Mumbai,1.0,9500.0,Diya,9500.0
2,O103,02-07-2026,Chair,Furniture,Surat,2.0,4500.0,Rohan,9000.0
31,O132,16-07-2026,Visitor Chair,Furniture,Surat,4.0,2200.0,Priya,8800.0
8,O109,05-07-2026,Office Chair,Furniture,Mumbai,1.0,7800.0,Aarav,7800.0
33,O134,17-07-2026,Bluetooth Speaker,Electronics,Ahmedabad,2.0,3800.0,Diya,7600.0
13,O114,07-07-2026,Bookshelf,Furniture,Surat,1.0,6500.0,Diya,6500.0
22,O123,12-07-2026,Side Table,Furniture,Surat,2.0,3200.0,Rohan,6400.0
14,O115,08-07-2026,Webcam,Electronics,Mumbai,2.0,3200.0,Rohan,6400.0
25,O126,13-07-2026,Drawer Unit,Furniture,Surat,1.0,5400.0,Diya,5400.0
21,O122,11-07-2026,Router,Electronics,Ahmedabad,2.0,2600.0,Diya,5200.0
4,O105,03-07-2026,Desk,Furniture,Surat,1.0,4950.0,Aarav,4950.0
19,O120,10-07-2026,Headphones,Electronics,Surat,2.0,2400.0,Priya,4800.0
11,O112,06-07-2026,USB Drive,Electronics,Mumbai,4.0,900.0,Priya,3600.0
10,O111,06-07-2026,Desk Lamp,Furniture,Surat,2.0,1800.0,Rohan,3600.0
27,O128,14-07-2026,Power Bank,Electronics,Ahmedabad,2.0,1800.0,Priya,3600.0
3,O104,02-07-2026,Keyboard,Electronics,Ahmedabad,2.0,1500.0,Priya,3000.0
20,O121,11-07-2026,Whiteboard,Stationery,Mumbai,1.0,2200.0,Aarav,2200.0
1,O102,01-07-2026,Mouse,Electronics,Mumbai,3.0,700.0,Diya,2100.0
26,O127,14-07-2026,Calculator,Stationery,Mumbai,3.0,650.0,Rohan,1950.0
15,O116,08-07-2026,Marker Pack,Stationery,Ahmedabad,6.0,300.0,Priya,1800.0
18,O119,10-07-2026,Paper Ream,Stationery,Ahmedabad,5.0,350.0,Rohan,1750.0
7,O108,04-07-2026,Pen Set,Stationery,Surat,5.0,250.0,Priya,1250.0
12,O113,07-07-2026,File Folder,Stationery,Ahmedabad,8.0,120.0,Aarav,960.0
32,O133,17-07-2026,Envelope Pack,Stationery,Mumbai,6.0,160.0,Aarav,960.0
29,O130,15-07-2026,Sticky Notes,Stationery,Mumbai,10.0,90.0,Diya,900.0
6,O107,04-07-2026,Notebook,Stationery,Ahmedabad,10.0,80.0,Rohan,800.0
23,O124,12-07-2026,Stapler,Stationery,Mumbai,4.0,180.0,Priya,720.0

In [28]:
df.sort_values(by="Sales",ascending=False).head()

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson,Sales
0,O101,01-07-2026,Laptop,Electronics,Surat,1.0,52000.0,Aarav,52000.0
30,O131,16-07-2026,Projector,Electronics,Ahmedabad,1.0,42000.0,Rohan,42000.0
24,O125,13-07-2026,Smartphone,Electronics,Ahmedabad,1.0,34000.0,Aarav,34000.0
16,O117,09-07-2026,Tablet,Electronics,Surat,1.0,28000.0,Aarav,28000.0
5,O106,03-07-2026,Monitor,Electronics,Mumbai,2.0,12500.0,Diya,25000.0

In [26]:
df.sort_values(by="Sales",ascending=False).tail(3)

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson,Sales
29,O130,15-07-2026,Sticky Notes,Stationery,Mumbai,10.0,90.0,Diya,900.0
6,O107,04-07-2026,Notebook,Stationery,Ahmedabad,10.0,80.0,Rohan,800.0
23,O124,12-07-2026,Stapler,Stationery,Mumbai,4.0,180.0,Priya,720.0

In [27]:
df.sort_values(by=["City","Sales"],ascending=False).head()

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson,Sales
0,O101,01-07-2026,Laptop,Electronics,Surat,1.0,52000.0,Aarav,52000.0
16,O117,09-07-2026,Tablet,Electronics,Surat,1.0,28000.0,Aarav,28000.0
28,O129,15-07-2026,Meeting Table,Furniture,Surat,1.0,14500.0,Aarav,14500.0
2,O103,02-07-2026,Chair,Furniture,Surat,2.0,4500.0,Rohan,9000.0
31,O132,16-07-2026,Visitor Chair,Furniture,Surat,4.0,2200.0,Priya,8800.0

In [30]:
df.sort_values(by="Sales",ascending=False).head(1)

,Order_ID,Date,Product,Category,City,Quantity,Price,Salesperson,Sales
0,O101,01-07-2026,Laptop,Electronics,Surat,1.0,52000.0,Aarav,52000.0

Part F : Grouping

In [32]:
total_sale= df.groupby("City")["Sales"].sum()
total_sale

City
Ahmedabad    117210.0
Mumbai        61130.0
Surat        145200.0
Name: Sales, dtype: float64

In [33]:
total_sale= df.groupby("Category")["Sales"].sum()
total_sale

Category
Electronics    233800.0
Furniture       76450.0
Stationery      13290.0
Name: Sales, dtype: float64

In [35]:
handle_by=df.groupby("Salesperson")["Order_ID"].count()
handle_by

Salesperson
Aarav    9
Diya     9
Priya    8
Rohan    8
Name: Order_ID, dtype: int64

In [36]:
total_sale= df.groupby("Salesperson")["Sales"].sum()
total_sale

Salesperson
Aarav    145370.0
Diya      78700.0
Priya     27570.0
Rohan     71900.0
Name: Sales, dtype: float64

In [38]:
total_quantity = df.groupby("Category")["Quantity"].sum()
total_quantity

Category
Electronics    26.0
Furniture      16.0
Stationery     58.0
Name: Quantity, dtype: float64

In [ ]:
avg_total_sale= df.groupby("City")["Sales"].mean()
avg_total_sale

City
Ahmedabad    10655.454545
Mumbai        5557.272727
Surat        12100.000000
Name: Sales, dtype: float64

In [45]:
total_sale= df.groupby(["City","Category"])["Sales"].sum()
total_sale

City       Category
Ahmedabad  Electronics    111900.0
           Stationery       5310.0
Mumbai     Electronics     37100.0
           Furniture       17300.0
           Stationery       6730.0
Surat      Electronics     84800.0
           Furniture       59150.0
           Stationery       1250.0
Name: Sales, dtype: float64

In [47]:
total_everything= df.groupby("Category")["Sales"].agg(["count","sum","mean","min","max"])
total_everything

             count       sum     mean     min      max
Category
Electronics     14  233800.0  16700.0  2100.0  52000.0
Furniture       10   76450.0   7645.0  3600.0  14500.0
Stationery      10   13290.0   1329.0   720.0   2200.0

Part G :Management Question

In [52]:
total_sales_by_city = df.groupby('City')['Sales'].sum()

best_city = total_sales_by_city.idxmax()
highest_sales = total_sales_by_city.max()
print(f"City with highest sales: {best_city}")
print(f"Total Sales: {highest_sales}")

City with highest sales: Surat
Total Sales: 145200.0

In [53]:
total_sales_by_city = df.groupby('Category')['Sales'].sum()

best_city = total_sales_by_city.idxmax()
highest_sales = total_sales_by_city.max()
print(f"Category with highest sales: {best_city}")
print(f"Total Sales: {highest_sales}")

Category with highest sales: Electronics
Total Sales: 233800.0